# Generated by Django 2.0.9 on 2019-02-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturls',
            name='short',
            field=models.CharField(max_length=14),
        ),
    ]
