# Generated by Django 2.0.9 on 2019-02-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0002_auto_20190217_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturls',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shorturls',
            name='short',
            field=models.CharField(blank=True, max_length=14, unique=True),
        ),
    ]
