# Generated by Django 2.0.9 on 2019-02-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0003_auto_20190217_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='shorturlsmanager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
